### ISSUE TITLE
Will Sesame extend Backbone?

### ISSUE THREAD

**Issue by ianmstew** [MarionetteLabs/Sesame.js#8]
Or start from scratch?  It has major implications on how we handle the view layer, at the very least (#5).

**Comment by jasonLaster** [comment]
I'm on the fence. I think I'd it for no because we'd have the freedom to build what we want to see.

**Comment by jamesplease** [comment]
Start from scratch, I think.

**Comment by ianmstew** [comment]
I agree.  I think that answers this question well enough for now.
